version: '3.8'

services:
  app:
    build: .
    ports:
      - "7066:5000"
    env_file:
      - .env  # Подключаем .env файл
    environment:
      - FLASK_ENV=production
    restart: unless-stopped