services:
  app:
    image: sims-mods-backend:${APP_VERSION:-latest}
    build: .
    ports:
      - "7066:7066"
    env_file:
      - .env
    volumes:
      - ./sims_mods.db:/app/sims_mods.db
    restart: unless-stopped

  frontend:
    image: sims-mods-frontend:${APP_VERSION:-latest}
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - app
    restart: unless-stopped