services:
  app:
    image: ssilurs/sims-mods-backend:${TAG:-latest}
    ports:
      - "7066:7066"
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    image: ssilurs/sims-mods-frontend:${TAG:-latest}
    ports:
      - "8081:80"
    depends_on:
      - app
    restart: unless-stopped